#!/usr/bin/env bun
/**
 * Generates the fixtures that pin `edm_core::js` to the JavaScript engine that
 * actually runs `market-request.ts`.
 *
 * These are measurements, not assertions. Where a fixture disagrees with the
 * Rust implementation, the fixture is right: it is what the original program
 * does. The corpus is deterministic (a fixed-seed PRNG) so regenerating it
 * produces a reviewable diff rather than noise.
 *
 *   bun xtask/oracle/bless-js.ts crates/edm-core/tests/fixtures
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const outDir = process.argv[2] ?? "crates/edm-core/tests/fixtures";
mkdirSync(outDir, { recursive: true });

/** Deterministic PRNG — mulberry32. */
function rng(seed: number): () => number {
  return () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = seed;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A double's exact bit pattern, so the fixture round-trips without ambiguity. */
const bitsOf = (() => {
  const buf = new DataView(new ArrayBuffer(8));
  return (v: number): string => {
    buf.setFloat64(0, v);
    return buf.getBigUint64(0).toString(16).padStart(16, "0");
  };
})();

function header(what: string): string {
  return `# ${what}\n# generated by xtask/oracle/bless-js.ts under bun ${Bun.version}\n# DO NOT EDIT — run \`cargo xtask bless\`\n`;
}

function write(name: string, what: string, rows: string[]): void {
  writeFileSync(join(outDir, name), header(what) + rows.join("\n") + "\n");
  console.log(`${name}: ${rows.length} rows`);
}

// ---------------------------------------------------------------------------
// The numeric corpus: boundaries first, then sampled magnitudes.
// ---------------------------------------------------------------------------

const boundaries: number[] = [
  0, -0, 1, -1, 0.5, -0.5, 0.1, 0.2, 0.3, 1 / 3, 2 / 3,
  0.15, 0.25, -0.25, 0.35, 0.45, 1.005, 2.675, 8.835,
  0.49999999999999994, 0.5000000000000001, -2.5, 2.5, -1.5, 1.5,
  1e-7, 1e-6, 1e-5, 1e20, 1e21, 1e22, 1e23, 1e31,
  Number.MAX_SAFE_INTEGER, -Number.MAX_SAFE_INTEGER,
  Number.MAX_SAFE_INTEGER + 2, 2 ** 53, 2 ** 53 + 2, 2 ** 64,
  Number.MAX_VALUE, Number.MIN_VALUE, 5e-324, Number.EPSILON,
  123456789, -987654321, 4306502403, 128049204, 4294967294, 4294967295,
  72060832334024995, 5378909424384,
  1234567.891, -1234567.891, 999999.9999, 1000000.0001,
  NaN, Infinity, -Infinity,
];

const numbers: number[] = [...boundaries];
{
  const r = rng(0x5eed);
  for (let i = 0; i < 700; i++) {
    // Sample across the whole exponent range, both signs.
    const exp = Math.floor(r() * 60) - 25;
    const mant = r() * 10;
    numbers.push((r() < 0.5 ? -1 : 1) * mant * 10 ** exp);
  }
  for (let i = 0; i < 300; i++) {
    // Integers, which is what most of this program actually formats.
    numbers.push(Math.floor(r() * 10 ** Math.floor(1 + r() * 17)));
  }
  for (let i = 0; i < 200; i++) {
    // Values with one significant fractional digit, for toFixed.
    numbers.push(Math.round(r() * 20000 - 10000) / 20);
  }
}

write("js_number.tsv", "Number.prototype.toString(10) — bits<TAB>expected", [
  ...numbers.map((v) => `${bitsOf(v)}\t${String(v)}`),
]);

write(
  "thousands.tsv",
  "Math.trunc(v).toLocaleString('en-US') for finite v — bits<TAB>expected",
  numbers
    .filter((v) => Number.isFinite(v))
    .map((v) => `${bitsOf(v)}\t${Math.trunc(v).toLocaleString("en-US")}`),
);

write(
  "to_fixed_1.tsv",
  "Number.prototype.toFixed(1) — bits<TAB>expected",
  numbers.map((v) => `${bitsOf(v)}\t${v.toFixed(1)}`),
);

// ---------------------------------------------------------------------------
// toISOString, via the guard formatUnixSeconds actually uses.
// ---------------------------------------------------------------------------

const instants: number[] = [
  0, 1, -1, 1000, -1000, 8.64e15, -8.64e15, 8.64e15 + 1, -8.64e15 - 1,
  1e12, -1e12, 253402300799999, -62135596800000, 1.5, -1.5, NaN, Infinity,
];
{
  const r = rng(0xda7e);
  for (let i = 0; i < 500; i++) {
    instants.push(Math.floor((r() * 2 - 1) * 8.64e15));
  }
}

write(
  "iso8601.tsv",
  "new Date(ms).toISOString(), or `-` when getTime() is not finite — bits<TAB>expected",
  instants.map((ms) => {
    const d = new Date(ms);
    const ok = Number.isFinite(d.getTime());
    return `${bitsOf(ms)}\t${ok ? d.toISOString() : "-"}`;
  }),
);

// ---------------------------------------------------------------------------
// Number(string) and the two trimming predicates.
// ---------------------------------------------------------------------------

const strings: string[] = [
  "", " ", "  12  ", "12", "-12", "+12", "0x10", "0X10", "0b101", "0o17",
  "1e3", "1E3", "1e+3", "1e-3", ".5", "5.", "5.0", "Infinity", "-Infinity",
  "+Infinity", "infinity", "inf", "nan", "NaN", "1_0", "1,0", "0x", "0b",
  "12abc", "abc", "\t12\n", " 12 ", "﻿12", "12",
  "᠎12", "​12", "1e", "1e+", "--1", "1-", " ", "\n", "\r\n",
  "9007199254740993", "0.1", "1e309", "1e-400", "-0", "00", "007",
];
{
  const r = rng(0xc0de);
  const alphabet = "0123456789+-.eExXbBoOaf_, \t ";
  for (let i = 0; i < 600; i++) {
    let s = "";
    const n = 1 + Math.floor(r() * 8);
    for (let j = 0; j < n; j++) {
      s += alphabet[Math.floor(r() * alphabet.length)];
    }
    strings.push(s);
  }
}

write(
  "to_number.tsv",
  "Number(s) — JSON-escaped input<TAB>String(Number(s))",
  strings.map((s) => `${JSON.stringify(s)}\t${String(Number(s))}`),
);

{
  // Every code point that could plausibly be whitespace, measured through all
  // three predicates the program relies on.
  const points: number[] = [];
  for (let c = 0; c <= 0x3000; c++) points.push(c);
  for (const c of [0x0085, 0x180e, 0x200b, 0xfeff, 0x2028, 0x2029, 0x205f, 0x3000]) {
    points.push(c);
  }
  const rows = points.map((c) => {
    const ch = String.fromCodePoint(c);
    const trimmed = `${ch}1${ch}`.trim() === "1";
    const numeric = Number(`${ch}1${ch}`) === 1;
    const regex = /^\s$/.test(ch);
    return `${c.toString(16).padStart(4, "0")}\t${+trimmed}\t${+numeric}\t${+regex}`;
  });
  write(
    "trim.tsv",
    "codepoint<TAB>String.trim strips<TAB>Number() strips<TAB>regex \\s matches",
    rows,
  );
}

// ---------------------------------------------------------------------------
// localeCompare. The ASCII permutation pins the primary order outright; the
// sampled pairs catch anything the permutation alone would miss.
// ---------------------------------------------------------------------------

{
  // Printable ASCII, Latin-1 Supplement and Latin Extended-A. Elite Dangerous
  // system and station names are full of the latter two, so an ASCII-only
  // corpus would leave the interesting half of the collation untested.
  const singles: string[] = [];
  for (let c = 0x20; c < 0x7f; c++) singles.push(String.fromCharCode(c));
  for (let c = 0xa0; c <= 0x17f; c++) singles.push(String.fromCharCode(c));
  const sorted = [...singles].sort((a, b) => a.localeCompare(b));
  const rows = [`# single-character order, sorted by localeCompare`];
  rows.push(sorted.map((c) => c.codePointAt(0)!.toString(16).padStart(4, "0")).join(" "));

  const words = [
    "gold", "Gold", "GOLD", "silver", "Silver", "agronomic treatment",
    "AgronomicTreatment", "a", "A", "ab", "Ab", "aB", "AB", "a b", "a-b",
    "a_b", "ab ", " ab", "", "1", "10", "2", "z", "Z", "$foo", "_foo",
    "-foo", "(foo)", "foo!", "Jaques Station", "jaques station",
    "hyades sector ni-x a16-0", "Hyades Sector NI-X a16-0",
    // Diacritics, ligatures and the letters that do not decompose.
    "Öl", "ol", "Ol", "öl", "OEl", "oel", "straße", "STRASSE", "strasse",
    "Boethold", "Böthold", "Bothold", "resume", "résumé", "RESUME",
    "Ångström", "Angstrom", "angstrom", "æther", "aether", "Æther",
    "Ørsted", "Orsted", "orsted", "Łódź", "Lodz", "lodz", "Þor", "Thor",
    "Ðelta", "Delta", "naïve", "naive", "co-op", "coop", "co op",
    "Sanchez", "Sánchez", "sanchez", "Nuñez", "Nunez", "Zulu", "Ötzi",
  ];
  const r = rng(0xa11ce);
  const pairs: string[] = [];
  // Exhaustive over the curated words, so nothing depends on sampling luck.
  for (const a of words) {
    for (const b of words) {
      pairs.push(`${JSON.stringify(a)}\t${JSON.stringify(b)}\t${Math.sign(a.localeCompare(b))}`);
    }
  }
  // Plus random Latin-1 strings, which reach combinations no curated list would.
  const pool = [...singles, ...words.join("")];
  for (let i = 0; i < 1500; i++) {
    const mk = () => {
      let s = "";
      for (let j = 0, n = 1 + Math.floor(r() * 5); j < n; j++) {
        s += pool[Math.floor(r() * pool.length)];
      }
      return s;
    };
    const [a, b] = [mk(), mk()];
    pairs.push(`${JSON.stringify(a)}\t${JSON.stringify(b)}\t${Math.sign(a.localeCompare(b))}`);
  }
  rows.push("# pairs: a<TAB>b<TAB>sign(a.localeCompare(b))");
  rows.push(...pairs);
  write("collate.txt", "localeCompare under the default locale", rows);
}

// ---------------------------------------------------------------------------
// JSON: enumeration order and round-trip serialization.
//
// The documents are built as *text*, not by stringifying an object, so that
// document order and duplicate keys survive into the fixture — both of which
// JSON.parse observes and neither of which a JS object literal could express.
// ---------------------------------------------------------------------------

{
  const r = rng(0x1501);

  const keyPool = [
    // Canonical array indices, which ECMAScript hoists.
    "0", "1", "2", "9", "10", "42", "1000", "4294967293", "4294967294",
    // One past the limit, and beyond: ordinary string keys.
    "4294967295", "4294967296", "9007199254740993",
    // Near-miss shapes that must NOT be treated as indices.
    "01", "007", "1.5", "1e3", "-1", "+1", " 1", "1 ", "", "0x1", "١",
    // Real ids from the two maps that straddle the boundary.
    "128049204", "128049152", "128673845", "4306502403", "128667761",
    // Ordinary names.
    "name", "id", "stock", "buyPrice", "commodities", "zzz", "Aaa",
  ];

  const valuePool = [
    "0", "-0", "1", "1.0", "-1", "0.1", "1e21", "1e-7", "123456789012345678901",
    "72060832334024995", "9007199254740993", "1.7976931348623157e308",
    '"str"', '"a\\"b"', '"tab\\there"', '"\\u001f"', '"é☃"', "true", "false",
    "null", "[]", "{}", "[1,2,3]", '{"a":1}', '{"1":"one","0":"zero"}',
  ];

  const docs: string[] = [
    // Hand-picked shapes that pin the specific claims in PORTING.md R5/R6.
    '{"2":"b","1":"a","0":"c"}',
    '{"b":1,"0":2,"a":3,"1":4}',
    '{"4294967295":"plain","4294967294":"index","0":"index"}',
    '{"a":1,"b":2,"a":3}',
    '{"01":"x","1":"y"}',
    '{"128049204":{},"128049152":{},"128673845":{}}',
    '{"4306502403":{},"128667761":{},"3223343616":{}}',
    "{}",
    "[]",
    '{"n":1e21}',
    '{"n":-0}',
    '{"n":1.0}',
    '{"n":72060832334024995}',
    '{"deep":{"deeper":{"deepest":[1,{"k":"v"}]}}}',
  ];

  for (let i = 0; i < 600; i++) {
    const n = 1 + Math.floor(r() * 7);
    const parts: string[] = [];
    for (let j = 0; j < n; j++) {
      const k = keyPool[Math.floor(r() * keyPool.length)]!;
      const v = valuePool[Math.floor(r() * valuePool.length)]!;
      parts.push(`${JSON.stringify(k)}:${v}`);
    }
    docs.push(`{${parts.join(",")}}`);
  }

  const rows: string[] = [];
  for (const doc of docs) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(doc);
    } catch {
      continue; // a generated document that JS itself rejects teaches nothing
    }
    const keys = Array.isArray(parsed) || typeof parsed !== "object" || parsed === null
      ? []
      : Object.keys(parsed as object);
    rows.push(
      [
        JSON.stringify(doc),
        JSON.stringify(keys),
        JSON.stringify(JSON.stringify(parsed)),
        JSON.stringify(JSON.stringify(parsed, null, 2)),
      ].join("\t"),
    );
  }
  write(
    "json.tsv",
    "doc<TAB>Object.keys<TAB>JSON.stringify<TAB>JSON.stringify(_,null,2) — all JSON-quoted",
    rows,
  );
}

console.log(`\nwrote fixtures to ${outDir} using bun ${Bun.version}`);
